[lab_workers]
x01 ansible_host=131.159.8.66

[management]
x02 ansible_host=131.159.8.68

[docker_workers]
# Future Docker-specific worker VMs go here, for example:
# x03 ansible_host=x03lp1.ucc.cit.tum.de

[platform:children]
lab_workers
management

[platform:vars]
ansible_user=root
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
