[lab_workers]
x01 ansible_host=x01lp1.ucc.cit.tum.de

[management]
x02 ansible_host=x02lp1.ucc.cit.tum.de

[platform:children]
lab_workers
management

[platform:vars]
ansible_user=CHANGE_ME
ansible_python_interpreter=/usr/bin/python3
