"""Validate lab scenario contracts and referenced repository artifacts."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

import jsonschema
import yaml

SECTION_RE = re.compile(r"^(#{2,4})\s+(.+)$", re.MULTILINE)
FORBIDDEN_HOST_MOUNT_FRAGMENTS = (
    "docker.sock",
    "podman.sock",
    "/run/podman",
    "/var/run/podman",
)


def _load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise TypeError(f"{path} must contain a YAML mapping")
    return data


def _extract_headings(path: Path) -> list[str]:
    """Extract all level-2 markdown headings from a file."""
    content = path.read_text(encoding="utf-8")
    return [
        f"{m.group(1)} {m.group(2).strip()}"
        for m in SECTION_RE.finditer(content)
        if len(m.group(1)) == 2
    ]


def _check_sections(guide_path: Path, template_sections: list[str], label: str) -> list[str]:
    guide_sections = _extract_headings(guide_path)
    guide_set, template_set = set(guide_sections), set(template_sections)

    errors: list[str] = [
        f"{guide_path}: missing {label} section {section!r}" for section in template_set - guide_set
    ]
    errors.extend(
        f"{guide_path}: unexpected {label} section {section!r} (not in template)"
        for section in sorted(guide_set - template_set)
    )
    return errors


def validate_scenario(schema: dict[str, Any], scenario_path: Path) -> list[str]:
    errors: list[str] = []
    scenario_dir = scenario_path.parent

    try:
        scenario = _load_yaml(scenario_path)
        jsonschema.validate(instance=scenario, schema=schema)
    except (OSError, ValueError, jsonschema.ValidationError) as exc:
        return [f"{scenario_path}: {exc}"]

    services = scenario.get("services", {})
    resources = scenario.get("resources", {})

    # Every container must reference a service that exists in services:
    # "workstation" is always valid — it is auto-generated by labctl.
    container_hostnames: set[str] = {"workstation"}
    for i, cdef in enumerate(scenario.get("containers", [])):
        svc = cdef.get("service", "")
        if svc and svc not in services:
            errors.append(
                f"{scenario_path}: containers[{i}].service={svc!r} not in scenario.services"
            )
        hostname = cdef.get("hostname", "")
        if hostname:
            container_hostnames.add(hostname)
        if svc and svc not in resources:
            errors.append(
                f"{scenario_path}: resources missing entry for containers[{i}].service={svc!r}"
            )
        security = cdef.get("security", {})
        if security.get("privileged"):
            errors.append(f"{scenario_path}: containers[{i}] must not set security.privileged=true")
        if security.get("host_network"):
            errors.append(
                f"{scenario_path}: containers[{i}] must not set security.host_network=true"
            )
        if "ALL" in security.get("cap_add", []):
            errors.append(f"{scenario_path}: containers[{i}] must not set security.cap_add=[ALL]")
        for volume in cdef.get("volumes", []):
            host_path = str(volume.get("host_path", ""))
            if any(fragment in host_path for fragment in FORBIDDEN_HOST_MOUNT_FRAGMENTS):
                errors.append(
                    f"{scenario_path}: containers[{i}].volumes must not mount "
                    f"host runtime socket path {host_path!r}"
                )

    if "workstation" not in resources:
        errors.append(f"{scenario_path}: resources missing entry for workstation")

    # workstation.depends_on must reference existing container hostnames
    ws_cfg = scenario.get("workstation", {})
    ws_errors = [
        f"{scenario_path}: workstation.depends_on={dep!r} does not match any containers[].hostname"
        for dep in ws_cfg.get("depends_on", [])
        if dep not in container_hostnames
    ]
    errors.extend(ws_errors)

    # checker exec_in must match a container hostname
    for check_def in scenario.get("checker", {}).get("checks", []):
        exec_in = check_def.get("exec_in")
        if exec_in and exec_in not in container_hostnames:
            errors.append(
                f"{scenario_path}: checker.exec_in={exec_in!r} "
                f"does not match any containers[].hostname"
            )

    for image in scenario.get("build", {}).get("images", []):
        dockerfile = image.get("dockerfile")
        if isinstance(dockerfile, str):
            path = scenario_dir / dockerfile
            if not path.is_file():
                errors.append(f"missing dockerfile: {path}")

    return errors


def validate_lab_docs(
    scenario_path: Path,
    repo_root: Path,
    student_guide_sections: list[str],
    instructor_guide_sections: list[str],
) -> list[str]:
    errors: list[str] = []
    lab_id = scenario_path.parent.name
    docs_dir = scenario_path.parent / "docs"

    student_guide = docs_dir / "student-guide.md"
    if not student_guide.is_file():
        errors.append(f"missing lab docs: {student_guide}")
    else:
        errors.extend(_check_sections(student_guide, student_guide_sections, "student-guide"))

    instructor_guide = docs_dir / "instructor-guide.md"
    if not instructor_guide.is_file():
        errors.append(f"missing lab docs: {instructor_guide}")
    else:
        errors.extend(
            _check_sections(instructor_guide, instructor_guide_sections, "instructor-guide")
        )

    solution_notes = docs_dir / "solution-notes.md"
    if not solution_notes.is_file():
        errors.append(f"missing lab docs: {solution_notes}")

    sitrep = docs_dir / "SITREP.txt"
    if not sitrep.is_file():
        errors.append(f"missing lab docs: {sitrep}")
    else:
        sitrep_content = sitrep.read_text(encoding="utf-8")
        expected_guide_path = f"/docs/labs/{lab_id}/"
        if expected_guide_path not in sitrep_content:
            errors.append(f"{sitrep}: must mention browser guide path {expected_guide_path}")

    mkdocs_include = repo_root / "docs" / "labs" / f"{lab_id}.md"
    if not mkdocs_include.is_file():
        errors.append(f"missing MkDocs include: {mkdocs_include}")
    else:
        content = mkdocs_include.read_text(encoding="utf-8")
        if "--8<--" not in content:
            errors.append(
                f"{mkdocs_include}: must use --8<-- snippet syntax to include "
                f"../../labs/{lab_id}/docs/student-guide.md"
            )

    return errors


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    labs_dir = repo_root / "labs"

    schema_path = labs_dir / "templates-contract" / "scenario.schema.json"
    try:
        with schema_path.open("r", encoding="utf-8") as handle:
            schema = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"failed to load {schema_path}: {exc}", file=sys.stderr)
        return 1

    student_template_path = labs_dir / "templates-contract" / "STUDENT_GUIDE_TEMPLATE.md"
    instructor_template_path = labs_dir / "templates-contract" / "INSTRUCTOR_GUIDE_TEMPLATE.md"

    if not student_template_path.is_file():
        print(f"missing student guide template: {student_template_path}", file=sys.stderr)
        return 1
    if not instructor_template_path.is_file():
        print(f"missing instructor guide template: {instructor_template_path}", file=sys.stderr)
        return 1

    scenario_template_path = labs_dir / "templates-contract" / "scenario.template.yaml"
    if scenario_template_path.is_file():
        try:
            scenario_template = _load_yaml(scenario_template_path)
            jsonschema.validate(instance=scenario_template, schema=schema)
        except (OSError, ValueError, jsonschema.ValidationError) as exc:
            print(f"{scenario_template_path}: {exc}", file=sys.stderr)
            return 1

    student_guide_sections = _extract_headings(student_template_path)
    instructor_guide_sections = _extract_headings(instructor_template_path)

    errors: list[str] = []
    for scenario_path in sorted(labs_dir.glob("*/scenario.yaml")):
        errors.extend(validate_scenario(schema, scenario_path))
        errors.extend(
            validate_lab_docs(
                scenario_path,
                repo_root,
                student_guide_sections,
                instructor_guide_sections,
            )
        )

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
