"""Validate lab scenario contracts and referenced repository artifacts."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

import jsonschema
import yaml

SECTION_RE = re.compile(r"^(#{2,4})\s+(.+)$", re.MULTILINE)
FORBIDDEN_HOST_MOUNT_FRAGMENTS = (
    "docker.sock",
    "podman.sock",
    "/run/podman",
    "/var/run/podman",
)

# Anti-spoiler patterns
_BASH_BLOCK_RE = re.compile(r"```bash\n(.*?)\n```", re.DOTALL)
_BASH_VERIFIER_BLOCK_RE = re.compile(r"```bash\s+verifier\n(.*?)\n```", re.DOTALL)
_ALL_BASH_BLOCKS_RE = re.compile(r"```bash(?:\s+verifier)?\n(.*?)\n```", re.DOTALL)
_QUOTED_STRING_RE = re.compile(r'["\']([^"\']{4,})["\']')


def _load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise TypeError(f"{path} must contain a YAML mapping")
    return data


def _extract_headings(path: Path) -> list[str]:
    """Extract all level-2 markdown headings from a file."""
    content = path.read_text(encoding="utf-8")
    return [
        f"{m.group(1)} {m.group(2).strip()}"
        for m in SECTION_RE.finditer(content)
        if len(m.group(1)) == 2
    ]


def _check_sections(guide_path: Path, template_sections: list[str], label: str) -> list[str]:
    guide_sections = _extract_headings(guide_path)
    guide_set, template_set = set(guide_sections), set(template_sections)

    errors: list[str] = [
        f"{guide_path}: missing {label} section {section!r}" for section in template_set - guide_set
    ]
    errors.extend(
        f"{guide_path}: unexpected {label} section {section!r} (not in template)"
        for section in sorted(guide_set - template_set)
    )
    return errors


def _extract_bash_blocks(content: str) -> list[str]:
    """Extract regular ```bash blocks."""
    return [m.group(1).strip() for m in _BASH_BLOCK_RE.finditer(content)]


def _extract_verifier_bash_blocks(content: str) -> list[str]:
    """Extract ```bash verifier blocks."""
    return [m.group(1).strip() for m in _BASH_VERIFIER_BLOCK_RE.finditer(content)]


def _extract_all_bash_blocks(content: str) -> list[str]:
    """Extract all bash blocks (regular and verifier)."""
    return [m.group(1).strip() for m in _ALL_BASH_BLOCKS_RE.finditer(content)]


def _extract_quoted_strings(content: str) -> set[str]:
    """Extract strings inside single or double quotes (4+ chars)."""
    return {m.group(1) for m in _QUOTED_STRING_RE.finditer(content)}


def _extract_section(content: str, heading: str) -> str:
    """Extract content under a markdown heading (case-insensitive)."""
    pattern = re.compile(
        r"^(#{2,4})\s+.*?\b" + re.escape(heading) + r"\b\s*$",
        re.MULTILINE | re.IGNORECASE,
    )
    match = pattern.search(content)
    if not match:
        return ""
    start = match.end()
    level = len(match.group(1))
    next_heading = re.compile(r"^#{1," + str(level) + r"}\s+", re.MULTILINE)
    next_match = next_heading.search(content, start)
    if next_match:
        return content[start : next_match.start()]
    return content[start:]


def validate_scenario(schema: dict[str, Any], scenario_path: Path) -> list[str]:
    errors: list[str] = []
    scenario_dir = scenario_path.parent

    try:
        scenario = _load_yaml(scenario_path)
        jsonschema.validate(instance=scenario, schema=schema)
    except (OSError, ValueError, jsonschema.ValidationError) as exc:
        return [f"{scenario_path}: {exc}"]

    services = scenario.get("services", {})
    resources = scenario.get("resources", {})

    # Every container must reference a service that exists in services:
    # "workstation" is always valid — it is auto-generated by labctl.
    container_hostnames: set[str] = {"workstation"}
    for i, cdef in enumerate(scenario.get("containers", [])):
        svc = cdef.get("service", "")
        if svc and svc not in services:
            errors.append(
                f"{scenario_path}: containers[{i}].service={svc!r} not in scenario.services"
            )
        hostname = cdef.get("hostname", "")
        if hostname:
            container_hostnames.add(hostname)
        if svc and svc not in resources:
            errors.append(
                f"{scenario_path}: resources missing entry for containers[{i}].service={svc!r}"
            )
        security = cdef.get("security", {})
        if security.get("privileged"):
            errors.append(f"{scenario_path}: containers[{i}] must not set security.privileged=true")
        if security.get("host_network"):
            errors.append(
                f"{scenario_path}: containers[{i}] must not set security.host_network=true"
            )
        if "ALL" in security.get("cap_add", []):
            errors.append(f"{scenario_path}: containers[{i}] must not set security.cap_add=[ALL]")
        for volume in cdef.get("volumes", []):
            host_path = str(volume.get("host_path", ""))
            if any(fragment in host_path for fragment in FORBIDDEN_HOST_MOUNT_FRAGMENTS):
                errors.append(
                    f"{scenario_path}: containers[{i}].volumes must not mount "
                    f"host runtime socket path {host_path!r}"
                )

    if "workstation" not in resources:
        errors.append(f"{scenario_path}: resources missing entry for workstation")

    # workstation.depends_on must reference existing container hostnames
    ws_cfg = scenario.get("workstation", {})
    ws_errors = [
        f"{scenario_path}: workstation.depends_on={dep!r} does not match any containers[].hostname"
        for dep in ws_cfg.get("depends_on", [])
        if dep not in container_hostnames
    ]
    errors.extend(ws_errors)

    # checker exec_in must match a container hostname
    for check_def in scenario.get("checker", {}).get("checks", []):
        exec_in = check_def.get("exec_in")
        if exec_in and exec_in not in container_hostnames:
            errors.append(
                f"{scenario_path}: checker.exec_in={exec_in!r} "
                f"does not match any containers[].hostname"
            )

    for image in scenario.get("build", {}).get("images", []):
        dockerfile = image.get("dockerfile")
        if isinstance(dockerfile, str):
            path = scenario_dir / dockerfile
            if not path.is_file():
                errors.append(f"missing dockerfile: {path}")

    return errors


def validate_lab_docs(
    scenario_path: Path,
    repo_root: Path,
    student_guide_sections: list[str],
    instructor_guide_sections: list[str],
) -> list[str]:
    errors: list[str] = []
    lab_id = scenario_path.parent.name
    docs_dir = scenario_path.parent / "docs"

    student_guide = docs_dir / "student-guide.md"
    if not student_guide.is_file():
        errors.append(f"missing lab docs: {student_guide}")
    else:
        errors.extend(_check_sections(student_guide, student_guide_sections, "student-guide"))

    instructor_guide = docs_dir / "instructor-guide.md"
    if not instructor_guide.is_file():
        errors.append(f"missing lab docs: {instructor_guide}")
    else:
        errors.extend(
            _check_sections(instructor_guide, instructor_guide_sections, "instructor-guide")
        )

    solution_notes = docs_dir / "solution-notes.md"
    if not solution_notes.is_file():
        errors.append(f"missing lab docs: {solution_notes}")

    sitrep = docs_dir / "SITREP.txt"
    if not sitrep.is_file():
        errors.append(f"missing lab docs: {sitrep}")
    else:
        sitrep_content = sitrep.read_text(encoding="utf-8")
        expected_guide_path = f"/docs/labs/{lab_id}/"
        if expected_guide_path not in sitrep_content:
            errors.append(f"{sitrep}: must mention browser guide path {expected_guide_path}")

    mkdocs_include = repo_root / "docs" / "labs" / f"{lab_id}.md"
    if not mkdocs_include.is_file():
        errors.append(f"missing MkDocs include: {mkdocs_include}")
    else:
        content = mkdocs_include.read_text(encoding="utf-8")
        if "--8<--" not in content:
            errors.append(
                f"{mkdocs_include}: must use --8<-- snippet syntax to include "
                f"../../labs/{lab_id}/docs/student-guide.md"
            )

    # ------------------------------------------------------------------
    # Anti-spoiler checks (requires both student-guide and solution-notes)
    # ------------------------------------------------------------------
    if student_guide.is_file() and solution_notes.is_file():
        sg_content = student_guide.read_text(encoding="utf-8")
        sn_content = solution_notes.read_text(encoding="utf-8")

        # 1. Verifier block check
        verifier_blocks = _extract_verifier_bash_blocks(sn_content)
        if not verifier_blocks:
            errors.append(f"{solution_notes}: must contain at least one ```bash verifier block")

        # 2. Bash block duplication (solution-notes verifier -> student-guide)
        # Only remediation/verifier bash blocks from solution-notes must not
        # appear in the student guide.
        sg_bash = _extract_bash_blocks(sg_content)
        sn_verifier_bash = _extract_verifier_bash_blocks(sn_content)
        for block in sn_verifier_bash:
            if block in sg_bash:
                errors.append(
                    f"{student_guide}: bash block duplicates remediation content from "
                    f"{solution_notes} (anti-spoiler violation)"
                )
                break

        # 3. Password/secret leakage (quoted strings from solution-notes)
        sn_quotes = _extract_quoted_strings(sn_content)
        for q in sn_quotes:
            if q in sg_content:
                errors.append(
                    f"{student_guide}: contains quoted string from "
                    f"{solution_notes} that may leak a secret/password: {q!r}"
                )
                break

        # 4. Official references in Remediate
        remediate_section = _extract_section(sg_content, "Remediate")
        if remediate_section:
            if not re.search(r"https?://|man\s+\w+", remediate_section):
                errors.append(
                    f"{student_guide}: Remediate section must contain an "
                    f"official documentation link or man reference"
                )
        else:
            errors.append(
                f"{student_guide}: missing Remediate section for official-reference check"
            )

        # 5. Hint ladder in Remediate
        if remediate_section:
            if not re.search(r"[Hh]int", remediate_section):
                errors.append(f"{student_guide}: Remediate section must contain a hint ladder")
        else:
            errors.append(f"{student_guide}: missing Remediate section for hint-ladder check")

        # 6. Evidence checkpoints
        if not re.search(r"[Ee]vidence checkpoint", sg_content):
            errors.append(f"{student_guide}: must contain at least one evidence checkpoint")

    return errors


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    labs_dir = repo_root / "labs"

    schema_path = labs_dir / "templates-contract" / "scenario.schema.json"
    try:
        with schema_path.open("r", encoding="utf-8") as handle:
            schema = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"failed to load {schema_path}: {exc}", file=sys.stderr)
        return 1

    student_template_path = labs_dir / "templates-contract" / "STUDENT_GUIDE_TEMPLATE.md"
    instructor_template_path = labs_dir / "templates-contract" / "INSTRUCTOR_GUIDE_TEMPLATE.md"

    if not student_template_path.is_file():
        print(f"missing student guide template: {student_template_path}", file=sys.stderr)
        return 1
    if not instructor_template_path.is_file():
        print(f"missing instructor guide template: {instructor_template_path}", file=sys.stderr)
        return 1

    scenario_template_path = labs_dir / "templates-contract" / "scenario.template.yaml"
    if scenario_template_path.is_file():
        try:
            scenario_template = _load_yaml(scenario_template_path)
            jsonschema.validate(instance=scenario_template, schema=schema)
        except (OSError, ValueError, jsonschema.ValidationError) as exc:
            print(f"{scenario_template_path}: {exc}", file=sys.stderr)
            return 1

    student_guide_sections = _extract_headings(student_template_path)
    instructor_guide_sections = _extract_headings(instructor_template_path)

    errors: list[str] = []
    for scenario_path in sorted(labs_dir.glob("*/scenario.yaml")):
        errors.extend(validate_scenario(schema, scenario_path))
        errors.extend(
            validate_lab_docs(
                scenario_path,
                repo_root,
                student_guide_sections,
                instructor_guide_sections,
            )
        )

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
