---
docker_rhel_repository_url: https://download.docker.com/linux/rhel/docker-ce.repo
docker_supported_architectures:
  - x86_64
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
