---
- name: Configure thesis management host
  hosts: management
  become: true
  roles:
    - role: common
      tags: [common, bootstrap]
    - role: podman
      tags: [podman, bootstrap]
    - management-services
